


WITH
  L0 AS (SELECT c FROM (SELECT 1 UNION ALL SELECT 1) AS D(c)),
  L1 AS (SELECT 1 AS c FROM L0 AS A CROSS JOIN L0 AS B),
  L2 AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS k FROM L1)
SELECT * FROM L2;
